Vagrant.configure("2") do |config|

   config.vm.synced_folder "~/shared", "/home/vagrant/shared", owner: "vagrant", group: "vagrant"
   config.vm.synced_folder "/media/automanuser/1TB/AutomanTools", "/storage", owner: "vagrant", group: "vagrant"

   config.vm.define 'automan-labeling' do |machine|
    machine.vm.box = "ubuntu/xenial64"
    config.disksize.size = "100GB"
    machine.vm.hostname = 'automan-labeling'
    machine.vm.network :private_network,ip: "192.168.33.33"
    machine.vm.network :forwarded_port, guest: 30080, host: 30080
    machine.vm.network :forwarded_port, guest: 8001, host: 8001
    machine.vm.provider "virtualbox" do |vbox|
      vbox.gui = false
      vbox.cpus = 6
      vbox.memory = 16384
    end

     machine.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "automan-labeling.yaml"
      ansible.version = "latest"
      ansible.verbose = false
      ansible.install = true
      ansible.limit = "automan-labeling"
      ansible.inventory_path = "hosts"
    end
  end
end
